language: go

go:
  - 1.2
  - 1.2.1
  - tip

script:
  - go test -bench=. -v ./... | grep -v 'no test files' ; test ${PIPESTATUS[0]} -eq 0
  - cd samples; find . -name "*.go" -print0 | xargs -0 -n1 go build
